name: Tag Release

on: push

env:
  PREFIX: release_v_

jobs:
  tag-release:
    name: Tag on Release
    runs-on: ubuntu-latest
    if: startsWith( github.event.head_commit.message, '$PREFIX' )
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@v3

      - name: Get Version
        uses: mad9000/actions-find-and-replace-string@3
        id: get-version
        with:
          source: ${{ github.ref }}
          find: '$PREFIX'
          replace: ''

      - name: Add Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{steps.get-version.outputs.value}}
          tag_prefix: ''