name: Tag Release

on:
  push:
    branches:
    - main

jobs:
  tag-release:
    name: Tag on Release
    runs-on: ubuntu-latest
    if: startsWith( github.event.head_commit.message, 'release_v_' )
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@v3

      - name: Get Version
        uses: mad9000/actions-find-and-replace-string@3
        id: get-version
        with:
          source: ${{ github.event.head_commit.message }}
          find: 'release_v_'
          replace: ''

      - name: Add Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{steps.get-version.outputs.value}}
          tag_prefix: ''
          