name: Tag Release

on: push

jobs:
  tag-release:
    name: Tag on Release
    runs-on: ubuntu-latest
    if: startsWith( github.event.head_commit.message, 'release_v_' )
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@v3

      - name: Get Version
        id: get-version
        run: echo '::set-output name=VERSION::${{ github.event.head_commit.message }}#"release_v_"'

      - name: Add Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{steps.get-version.outputs.VERSION}}